Repository Gallopsled/pwntools, pull requests merged in 2020-06, with the labels that each got.

#1526 Update Corefile warnings and replace asserts with normal checks
  pwnlib/elf/corefile.py
Labels: bug

#1540 Convert logging status messages to text
  pwnlib/log.py
Labels: enhancement

#1550 Add workaround for #1538 until Unicorn is fixed
  .github/workflows/ci.yml
Labels: testing

#1551 Increase fetch depth to 100 to increase cache hits
  .github/workflows/ci.yml
Labels: testing

#1542 Use tmux or screen if the environment variables are present, even if we detect an X11 terminal
  pwnlib/util/misc.py
Labels: enhancement

#1558 Recommend people use "pip install --upgrade pwntools"
  README.md
Labels: docs

#1536 Detect AVR binutils
  pwnlib/asm.py
Labels: feature

#1580 Sort dictionary fields before attempting to flatten them
  pwnlib/util/packing.py
Labels: bug

#1600 [ci] Delete foo-staging branch after merging and pushing foo
  .github/workflows/ci.yml
Labels: releases, testing

#1607 [docker] Get Travis CI dockerfile working more
  travis/docker/Dockerfile
  travis/docker/run.sh
Labels: testing

#1618 [aarch64] Fix aarch64.pushstr and pushstr_array
  CHANGELOG.md
  pwnlib/shellcraft/templates/aarch64/pushstr.asm
  pwnlib/shellcraft/templates/aarch64/pushstr_array.asm
  pwnlib/version.py
  setup.py
Labels: shellcode

#1620 [stable] Fix incorrectly-merged code
  pwnlib/shellcraft/templates/aarch64/pushstr_array.asm
Labels: bug, releases, shellcode
